import { PrismaClient, Prisma } from '@prisma/client'

const prisma = new PrismaClient()

//Pre-registered Favoureds
const favouredData: Prisma.FavouredCreateInput[] = [
    {
        name: 'Alice',
        email: 'alice@test.tst',
        cpf: '111.111.111-11',
        status: 'valid',
        account_bank: '237',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Alain',
        email: 'alain@test.tst',
        cpf: '222,222,222-22',
        status: 'draft',
        account_bank: '237',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Alan',
        email: 'alan@test.tst',
        cpf: '333.333.333-33',
        status: 'draft',
        account_bank: '237',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Alex',
        email: 'alex@test.tst',
        cpf: '444.444.444-44',
        status: 'draft',
        account_bank: '104',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Setembrino',
        email: 'setembrino@test.tst',
        cpf: '555.555.555-55',
        status: 'draft',
        account_bank: '001',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Josberto',
        email: 'josberto@test.tst',
        cpf: '666.666.666-66',
        status: 'draft',
        account_bank: '001',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Maricota',
        email: 'maricota@test.tst',
        cpf: '777.777.777-77',
        status: 'valid',
        account_bank: '756',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'favorecido',
        email: 'favorecido@test.tst',
        cpf: '888.888.888-88',
        status: 'draft',
        account_bank: '001',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Peter Parker',
        email: 'parker@test.tst',
        cpf: '999.999.999-99',
        status: 'draft',
        account_bank: '001',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'easy',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Moss',
        email: 'moss@test.tst',
        cpf: '000.000.000-00',
        status: 'draft',
        account_bank: '756',
        account_agency: '1234',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '123456',
        account_number_digit: '2',
    },
    {
        name: 'Epstein',
        email: 'epstein@didntkill.him.slf',
        cpf: '427.382.030-78',
        status: 'draft',
        account_bank: '001',
        account_agency: '641',
        account_agency_digit: '1',
        account_type: 'checking',
        account_number: '9875',
        account_number_digit: 'x',
    },
    {
        name: 'Bruce Banner',
        email: 'bruce@avengers.com',
        cpf: '701.000.970-81',
        status: 'valid',
        account_bank: '237',
        account_agency: '641',
        account_agency_digit: '1',
        account_type: 'checking',
        account_number: '9875',
        account_number_digit: 'x',
    },
    {
        name: 'Anthony Stark',
        email: 'tony@stark.com',
        cpf: '325.772.590-69',
        status: 'valid',
        account_bank: '001',
        account_agency: '981',
        account_agency_digit: '7',
        account_type: 'checking',
        account_number: '3697',
        account_number_digit: '2',
    },
    {
        name: 'Natasha Romanov',
        email: 'naty@mother.ru',
        cpf: '327.586.690-72',
        status: 'draft',
        account_bank: '756',
        account_agency: '812',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '468',
        account_number_digit: '9',
    },
    {
        name: 'Stephen Strange',
        email: 'strange@newyorkhealth.com',
        cpf: '284.468.690-71',
        status: 'draft',
        account_bank: '001',
        account_agency: '111',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '111',
        account_number_digit: '1',
    },
    {
        name: 'Adolin Kholin',
        email: 'adolin@kholins.com',
        cpf: '464.094.930-88',
        status: 'draft',
        account_bank: '104',
        account_agency: '6912',
        account_agency_digit: '4',
        account_type: 'checking',
        account_number: '689',
        account_number_digit: '2',
    },
    {
        name: 'Dalinar Kholin',
        email: 'dalinar@kholins.com',
        cpf: '402.392.880-17',
        status: 'valid',
        account_bank: '104',
        account_agency: '6912',
        account_agency_digit: '4',
        account_type: 'checking',
        account_number: '4441',
        account_number_digit: '3',
    },
    {
        name: 'Renarin Kholin',
        email: 'renarin@kholins.com',
        cpf: '704.791.500-10',
        status: 'draft',
        account_bank: '104',
        account_agency: '6912',
        account_agency_digit: '4',
        account_type: 'checking',
        account_number: '0666',
        account_number_digit: '7',
    },
    {
        name: 'Yusuke Urameshi',
        email: 'yu@yuhakusho.com',
        cpf: '453.367.330-91',
        status: 'draft',
        account_bank: '756',
        account_agency: '812',
        account_agency_digit: '0',
        account_type: 'checking',
        account_number: '305',
        account_number_digit: '0',
    },
    {
        name: 'Kurama',
        email: 'kurama@yuhakusho.com',
        cpf: '612.263.670-38',
        status: 'draft',
        account_bank: '756',
        account_agency: '3332',
        account_agency_digit: '9',
        account_type: 'checking',
        account_number: '313',
        account_number_digit: '0',
    },
    {
        name: 'Hiei',
        email: 'hiei@yuhakusho.com',
        cpf: '033.621.860-50',
        status: 'draft',
        account_bank: '756',
        account_agency: '0777',
        account_agency_digit: '9',
        account_type: 'checking',
        account_number: '717',
        account_number_digit: '7',
    },
    {
        name: 'Joe Rogan',
        email: 'joe@rogan.com',
        cpf: '068.044.310-06',
        status: 'valid',
        account_bank: '001',
        account_agency: '362',
        account_agency_digit: '1',
        account_type: 'easy',
        account_number: '123',
        account_number_digit: '1',
    },
    {
        name: 'Elon Musk',
        email: 'musk@tesla.com',
        cpf: '411.591.340-14',
        status: 'valid',
        account_bank: '001',
        account_agency: '710',
        account_agency_digit: '6',
        account_type: 'savings',
        account_number: '6122',
        account_number_digit: '8',
    },
    {
        name: 'Doge Coin',
        email: 'doge@coin.com',
        cpf: '591.833.730-04',
        status: 'valid',
        account_bank: '001',
        account_agency: '4848',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '1122',
        account_number_digit: '3',
    },
    {
        name: 'Shiba Coin',
        email: 'shib@coin.com',
        cpf: '631.022.960-50',
        status: 'valid',
        account_bank: '001',
        account_agency: '4848',
        account_agency_digit: '1',
        account_type: 'savings',
        account_number: '1122',
        account_number_digit: '3',
    },
    {
        name: 'Internet Explorer',
        email: 'internet@microsoft.com',
        cpf: '047.625.680-15',
        status: 'draft',
        account_bank: '237',
        account_agency: '1313',
        account_agency_digit: '22',
        account_type: 'checking',
        account_number: '00001',
        account_number_digit: '1',
    },
    {
        name: 'Bill Gates',
        email: 'william@microsoft.com',
        cpf: '218.943.300-21',
        status: 'draft',
        account_bank: '104',
        account_agency: '1100',
        account_agency_digit: '1',
        account_type: 'checking',
        account_number: '3325',
        account_number_digit: '0',
    },
    {
        name: 'Steve Jobs',
        email: 'jobs@pear.com',
        cpf: '089.479.750-60',
        status: 'draft',
        account_bank: '104',
        account_agency: '8892',
        account_agency_digit: '2',
        account_type: 'checking',
        account_number: '12127',
        account_number_digit: '0',
    },
    {
        name: 'Jotaro Kujo',
        email: 'jojo2@bizarre.com',
        cpf: '398.937.770-11',
        status: 'valid',
        account_bank: '756',
        account_agency: '31258',
        account_agency_digit: '7',
        account_type: 'checking',
        account_number: '3651',
        account_number_digit: '2',
    },
    {
        name: 'Joseph Joestar',
        email: 'jojo@bizarre.com',
        cpf: '342.471.840-83',
        status: 'valid',
        account_bank: '756',
        account_agency: '467',
        account_agency_digit: '5',
        account_type: 'checking',
        account_number: '810',
        account_number_digit: '5',
    },

]

//Banks
const bankData: Prisma.BankCreateInput[] = [
    {
        id: '001',
        name: 'Banco do Brasil',
    },
    {
        id: '104',
        name: 'Caixa Economica Federal',
    },
    {
        id: '237',
        name: 'Bradesco ',
    },
    {
        id: '756',
        name: 'Sicoob',
    },
]

//Seed the seeds
async function main() {
    console.log(`Seeding ...`)
    for (const f of favouredData) {
        const favoured = await prisma.favoured.create({
            data: f,
        })
        console.log(`Created favoured with id: ${favoured.id}`)
    }
    for (const b of bankData) {
        const bank = await prisma.bank.create({
            data: b,
        })
        console.log(`Created bank with id: ${bank.id}`)
    }
    console.log(`Seeding finished.`)
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })